repos:
- hooks:
  - args:
    - --markdown-linebreak-ext=md
    id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-toml
  - id: detect-private-key
  - args:
    - --maxkb=2560
    id: check-added-large-files
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
- hooks:
  - id: black
    language_version: python3.12.6
  repo: https://github.com/psf/black-pre-commit-mirror
  rev: 24.8.0
- hooks:
  - additional_dependencies:
    - bandit[toml]
    args:
    - -c
    - pyproject.toml
    - -r
    - .
    id: bandit
    pass_filenames: false
  repo: https://github.com/PyCQA/bandit
  rev: 1.7.10
- hooks:
  - id: commitizen
    stages:
    - commit-msg
  - id: commitizen-branch
    stages:
    - push
  repo: https://github.com/commitizen-tools/commitizen
  rev: v3.29.1
